(ns cleebo.views.imgs)

(def imgs
  [["1_01_baxter.jpg" "Baxter"]
   ["1_02_owen.jpg" "Owen"]
   ["1_03_more.jpg" "More"]
   ["1_04_milton.jpg" "Milton"]
   ["1_05_prynne.jpg" "Prynne"]
   ["1_06_taylor.jpg" "Taylor"]
   ["1_07_lestrange.jpg" "L'estrange"]
   ["1_08_fox.jpg" "Fox"]
   ["2_01_burnet.jpg" "Burnet"]
;   ["2_03_stillingfleet.jpg" "Stillingfleet"]
   ["2_04_boyle.jpg" "Boyle"]
   ["2_06_whitby.jpg" "Whitby"]
;   ["2_07_dryden.jpg" "Dryden"]
   ["2_09_penn.jpg" "Penn"]
   ["2_11_mather.jpg" "Mather"]
   ["2_13_tillotson.jpg" "Tillotson"]
   ["2_14_behn.jpg" "Behn"]
   ["2_15_bunyan.jpg" "Bunyan"]  
   ["2_16_willard.jpg" "Willard"]
   ["2_17_keach.jpg" "Keach"]
   ["2_18_salmon.jpg" "Salmon"]
   ["2_20_flavel.jpg" "Flavel"]
   ["2_22_poole.jpg" "Poole"]
   ["3_01_defoe.jpg" "Defoe"]
   ["3_02_swift.jpg" "Swift"]
   ["3_03_mather.jpg" "Mather"]
;   ["3_05_whiston.jpg" "Whiston"]
;   ["3_06_ward.jpg" "Ward"]
   ["3_07_wake.jpg" "Wake"]
   ["3_08_durfey.jpg" "Durfey"]
   ["4_01_addison.jpg" "Addison"]
   ["4_02_steele.jpg" "Steele"]
   ["4_03_clarke.jpg" "Clarke"]
   ["4_04_cibber.jpg" "Cibber"]
   ["4_06_haywood.jpg" "Haywood"]
   ["4_09_hoadly.jpg" "Hoadly"]
   ["x2_02_locke.jpg" "Locke"]
   ["x2_05_newton.jpg" "Newton"]])

(defn random-img []
  (let [n (rand-int (dec (count imgs)))
        [href name] (nth imgs n)]
    {:href href :name name}))
