(ns react-bootstrap.components
  (:require [reagent.core]
            [cljsjs.react-bootstrap])
  (:require-macros [react-bootstrap.adaptors :refer [bs-components]]))

(bs-components
 "Accordion"
 "Alert"
 "Badge"
 "Breadcrumb"
 "BreadcrumbItem"
 "Button"
 "ButtonGroup"
 "ButtonInput"
 "ButtonToolbar"
 "Carousel"
 "CarouselItem"
 "Col"
 "CollapsibleNav"
 "Dropdown"
 "DropdownButton"
 "Glyphicon"
 "Grid"
 "Image"
 "Input"
 "Interpolate"
 "Jumbotron"
 "Label"
 "ListGroup"
 "ListGroupItem"
 "MenuItem"
 "Modal"
 "ModalBody"
 "ModalFooter"
 "ModalHeader"
 "ModalTitle"
 "Nav"
 "Navbar"
 "NavBrand"
; "NavbarBrand" 
 "NavDropdown"
 "NavItem"
 "Overlay"
 "OverlayTrigger"
 "PageHeader"
 "PageItem"
 "Pager"
 "Pagination"
 "Panel"
 "PanelGroup"
 "Popover"
 "ProgressBar"
 "ResponsiveEmbed"
 "Row"
 "SafeAnchor"
 "SplitButton"
 "Tab"
 "Table"
 "Tabs"
 "Thumbnail"
 "Tooltip"
 "Well"
 "Collapse"
 "Fade")

(def dropdown-toggle
  (reagent.core/adapt-react-class js/ReactBootstrap.Dropdown.Toggle))

(def dropdown-menu
  (reagent.core/adapt-react-class js/ReactBootstrap.Dropdown.Menu))
