(ns cosycat.views.imgs)

(def imgs
  [["101_heylyn.jpg" "Heylyn"]
   ["102_prynne.jpg" "Prynne"]
   ["103_davenant.jpg" "Davenant"]
   ["104_fuller.jpg" "Fuller"]
   ["105_milton.jpg" "Milton"]
   ["106_taylor.jpg" "Taylor"]
   ["107_more.jpg" "More"]
   ["108_lilburne.jpg" "Lilburne"]
   ["109_baxter.jpg" "Baxter"]
   ["110_owen.jpg" "Owen"]
   ["111_lestrange.jpg" "Lestrange"]
   ["201_robertboyle.jpg" "Robertboyle"]
   ["203_poole.jpg" "Poole"]
   ["204_fox.jpg" "Fox"]
   ["207_bunyan.jpg" "Bunyan"]
   ["208_flavel.jpg" "Flavel"]
   ["209_tillotson.jpg" "Tillotson"]
   ["210_dryden.jpg" "Dryden"]
   ["301_stillingfleet.jpg" "Stillingfleet"]
   ["303_whitby.jpg" "Whitby"]
   ["305_mather.jpg" "Mather"]
   ["307_keach.jpg" "Keach"]
   ["309_shadwell.jpg" "Shadwell"]
   ["310_behn.jpg" "Behn"]
   ["312_burnet.jpg" "Burnet"]
   ["313_salmon.jpg" "Salmon"]
   ["314_penn.jpg" "Penn"]
   ["401_durfey.jpg" "Durfey"]
   ["402_wake.jpg" "Wake"]
   ["403_dennis.jpg" "Dennis"]
   ["405_defoe.jpg" "Defoe"]
   ["406_mather.jpg" "Mather"]
   ["408_swift.jpg" "Swift"]
   ["409_whiston.jpg" "Whiston"]
   ["410_ward.jpg" "Ward"]
   ["501_cibber.jpg" "Cibber"]
   ["502_steele.jpg" "Steele"]
   ["503_addison.jpg" "Addison"]
   ["505_clarke.jpg" "Clarke"]
   ["506_hoadly.jpg" "Hoadly"]])


(defn random-img []
  (let [n (rand-int (dec (count imgs)))
        [href name] (nth imgs n)]
    {:href (str "portraits/" href) :name name}))
